echo "Installing basic required software and development packages"
sudo apt-get update
sudo apt-get -y install \
    autoconf \
    automake \
    bridge-utils \
    build-essential \
    cmake \
    dnsmasq \
    doxygen \
    git \
    graphviz \
    htop \
    imagemagick \
    libaio-dev \
    libaom-dev \
    libaom3 \
    libaom-doc \
    libasound2-dev \
    libass-dev \
    libavcodec-dev \
    libavdevice-dev \
    libavfilter-dev \
    libavformat-dev \
    libavutil-dev \
    libfreetype6-dev \
    libgmp-dev \
    libmp3lame-dev \
    libopencore-amrnb-dev \
    libopencore-amrwb-dev \
    libopencv-dev \
    libopus-dev \
    libopus0 \
    librtmp-dev \
    libsdl2-dev \
    libsdl2-image-dev \
    libsdl2-mixer-dev \
    libsdl2-net-dev \
    libsdl2-ttf-dev \
    libsnappy-dev \
    libsoxr-dev \
    libssh-dev \
    libssl-dev \
    libtool \
    libusb-1.0-0-dev \
    libv4l-dev \
    libva-dev \
    libvdpau-dev \
    libvo-amrwbenc-dev \
    libvorbis-dev \
    libwebp-dev \
    libx11-dev \
    libx264-dev \
    libx265-dev \
    libxcb-shape0-dev \
    libxcb-shm0-dev \
    libxcb-xfixes0-dev \
    libxcb1-dev \
    libxml2-dev \
    libzimg2 \
    libzimg-dev \
    lzma-dev \
    meson \
    mlocate \
    nasm \
    openssh-server \
    pkg-config \
    python3-dev \
    python3-pip \
    texinfo \
    tree \
    wget \
    vim \
    xdotool \
    yasm \
    zlib1g-dev
